# Generated by Django 4.1.6 on 2023-02-03 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
        ('feedback_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='Feedback_id',
            field=models.ForeignKey(db_column='feedback_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='feedback_api.feedback'),
        ),
        migrations.AlterField(
            model_name='action',
            name='employee_id',
            field=models.ForeignKey(db_column='employee_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_api.employee'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='assigned_to',
            field=models.ForeignKey(db_column='employee_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_api.employee'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='customer_id',
            field=models.ForeignKey(db_column='customer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_api.customer'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='service_id',
            field=models.ForeignKey(db_column='service_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='feedback_api.service'),
        ),
    ]
