# Generated by Django 4.1.6 on 2023-02-05 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_api', '0002_alter_action_feedback_id_alter_action_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(default='Created', max_length=240, verbose_name='Name'),
        ),
    ]
